### ISSUE TITLE
Specialization for IO?

### ISSUE THREAD

**Issue by jatcwang** [ValdemarGr/catch-effect#6]
Are you open to contributions for API specialized for `IO`? I want to make this as simple as possible to adopt for those using IO and suffering for EitherT

**Comment by ValdemarGr** [comment]
That is a good idea. The docs (README) would also be more concise 🎉

**Comment by ValdemarGr** [comment]
What does your idea for a simpler API entail? Something like `import catcheffect.io.*` maybe?

**Comment by jatcwang** [comment]
I've put in a very barebone PR in #7. Let me know what you think!

Some other unrelated ideas from my own prototyping:

Instead of Raise I named it Abort, and instead of a `Raise#raise` method, I have `Abort#apply`, which allows the following API:

```
def doSomething()(implicit abort: Abort[DomainError]): IO[String] = {
  for {
    _ <- ...
    _ <-  abort(DomainError.Err1(..))
  } yield ...
}
```

I think `raise(DomainError.Err1(..))` will work well too but `abort` definitely _catches_ my attention more :smile:

**Comment by ValdemarGr** [comment]
It looks nice to not have to wire a `Catch` instance through the whole application :+1: 

The naming and structure of the current algebra stems from [cats-mtl](https://github.com/typelevel/cats-mtl/blob/091eeea25bdcd5c77b7f7b95f1735467c2c9c6db/core/src/main/scala/cats/mtl/Raise.scala#L66).

Have you also _handled_ naming for the IO-specialized instance of `Handle` in your prototype?

I don't think I have seen `apply` on an algebra before, I think `Abort[F]("error")` looks a bit funny, but maybe I have been trained to always expect a method after typeclass summoning :smiley:.

The only case of a specialized (and IO in fact) MTL typeclass is [IOLocal](https://github.com/typelevel/cats-effect/blob/2ce7e0ae00dbee82783a11fe3e087401c9c6df96/core/shared/src/main/scala/cats/effect/IOLocal.scala#L139), they also have another naming scheme for IO specialized datatypes [here](https://github.com/typelevel/cats-effect/blob/2ce7e0ae00dbee82783a11fe3e087401c9c6df96/core/shared/src/main/scala/cats/effect/package.scala#L72-L74) (a bit funny that one starts with IO[Local] and others end with [Outcome]IO).

Maybe we could add something akin to MTL extension methods? 
```scala
// not entirely sure this works nice with type inference
extension [A](a: A)
  def abort[F[_], E >: A, C](using raise: Raise[IO, E]): IO[C] = raise.raise(a: E)

def doSomething()(implicit raise: Raise[IO, DomainError]): IO[String] = {
  for {
    _ <- ...
    _ <-  DomainError.Err1(..).abort
  } yield ...
}
```
This needs more work since there are 3 type parameters which I get the feeling will cause inference problems. [This is how cats-mtl does it](https://github.com/typelevel/cats-mtl/blob/091eeea25bdcd5c77b7f7b95f1735467c2c9c6db/core/src/main/scala/cats/mtl/syntax/raise.scala#L25-L28).

**Comment by jatcwang** [comment]
No I didn't have a equivalent for Handle. Was just a clean room minimal prototype and I needed an alternative name for Raise :smile: 

As for the extension methods, I think for readability I prefer "operation first", so `R.raise(..)` is fine to me.

If you're happy with the IO API I'll continue to polish it :+1: Thanks!

**Comment by ValdemarGr** [comment]
I think the current implementation looks good 👍.
